### ISSUE TITLE
Upgrade/Uninstall wipes user directory

### ISSUE THREAD

**Issue by Cyntech** [frostwire/frostwire-desktop#410]
I don't personally use the program, however, a friend brought me their laptop claiming all their photos and music had disappeared.

On inspection, all media had been erased from their user directory (Windows 8). I recovered the files (what I could) and uninstalled FrostWire on their instruction. As it uninstalled, it nuked *everything* in the user directory, including settings, leaving the user profile pretty much stuffed.

I found a FrostWire 5 folder on the machine as well and version 6 was installed, so I'm suspecting that the upgrade from version 5 to 6 wiped it the first time, then the uninstall nuked it good and proper.

This is a show stopper, guys.

**Comment by gubatron** [comment]
our emails would be collapsed if this were true.

My thinking is that somehow your friend pointed or installed FrostWire inside his Photos folder, instead of say %PROGRAM_FILES%, or had his photos saving to %PROGRAM_FILES%/FrostWire/

Back on FrostWire 5 we used to just wipe the FrostWire installation folder (which was supposed to only have FrosWire binaries, and this is enforced when you select your download folder), but now, we make sure this doesn't happen anymore and we delete file by file (not a whole folder wipe) just to make sure this issue you report is impossible.

**Comment by gubatron** [comment]
Here's the code that prevents you from making your save folder the one where FrostWire might be installed.

https://github.com/frostwire/frostwire-desktop/blob/master/src/com/frostwire/gui/bittorrent/TorrentSaveFolderComponent.java#L109

Now that I think about it, this could fail if FrostWire is installed outside ProgramFiles, which may have been the case of your friend.

In whatever case, this is a very very rare fuck up by the user.
